package com.example.lee.newweather;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CITY".
 */
@Entity
public class City {

    @Id
    private String id;
    private String cityZh;
    private String provinceZh;
    private String leaderZh;

    @Generated
    public City() {
    }

    public City(String id) {
        this.id = id;
    }

    @Generated
    public City(String id, String cityZh, String provinceZh, String leaderZh) {
        this.id = id;
        this.cityZh = cityZh;
        this.provinceZh = provinceZh;
        this.leaderZh = leaderZh;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCityZh() {
        return cityZh;
    }

    public void setCityZh(String cityZh) {
        this.cityZh = cityZh;
    }

    public String getProvinceZh() {
        return provinceZh;
    }

    public void setProvinceZh(String provinceZh) {
        this.provinceZh = provinceZh;
    }

    public String getLeaderZh() {
        return leaderZh;
    }

    public void setLeaderZh(String leaderZh) {
        this.leaderZh = leaderZh;
    }

}
