package com.example.lee.newweather;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lee.newweather.City;
import com.example.lee.newweather.MyCity;

import com.example.lee.newweather.CityDao;
import com.example.lee.newweather.MyCityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig myCityDaoConfig;

    private final CityDao cityDao;
    private final MyCityDao myCityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        myCityDaoConfig = daoConfigMap.get(MyCityDao.class).clone();
        myCityDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        myCityDao = new MyCityDao(myCityDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(MyCity.class, myCityDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        myCityDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public MyCityDao getMyCityDao() {
        return myCityDao;
    }

}
